name: Trigger auto deployment for container-app-j4u2fq7s22teq

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-j4u2fq7s22teq-AutoDeployTrigger-f6e50c9e-9153-40c8-a809-be539986becb.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPJ4U2FQ7S22TEQ_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPJ4U2FQ7S22TEQ_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPJ4U2FQ7S22TEQ_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPJ4U2FQ7S22TEQ_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPJ4U2FQ7S22TEQ_REGISTRY_PASSWORD }}
          containerAppName: container-app-j4u2fq7s22teq
          resourceGroup: appspacesfastapibfaca8d4
          imageToBuild: default/container-app-j4u2fq7s22teq:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


